# Generated by Django 4.2.7 on 2023-11-22 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device_mgt', '0002_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gadget',
            name='issued_date',
            field=models.DateField(blank=True),
        ),
    ]
