# Generated by Django 4.2.7 on 2023-11-22 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('device_mgt', '0003_alter_gadget_issued_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gadget',
            name='issued_to',
        ),
    ]
